// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptBE.Data;

#nullable disable

namespace PromptBE.Migrations
{
    [DbContext(typeof(PromptDbContext))]
    partial class PromptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PromptBE.Models.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PromptBE.Models.CategoryPrompt", b =>
                {
                    b.Property<string>("PromptId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PromptId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryPrompts", (string)null);
                });

            modelBuilder.Entity("PromptBE.Models.Prompt", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Prompt");

                    b.HasKey("Id");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("PromptBE.Models.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("PromptBE.Models.TagPrompt", b =>
                {
                    b.Property<string>("PromptId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PromptId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TagPrompts", (string)null);
                });

            modelBuilder.Entity("PromptBE.Models.CategoryPrompt", b =>
                {
                    b.HasOne("PromptBE.Models.Category", "Category")
                        .WithMany("CategoryPrompts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptBE.Models.Prompt", "Prompt")
                        .WithMany("CategoryPrompts")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Prompt");
                });

            modelBuilder.Entity("PromptBE.Models.TagPrompt", b =>
                {
                    b.HasOne("PromptBE.Models.Prompt", "Prompt")
                        .WithMany("TagPrompts")
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PromptBE.Models.Tag", "Tag")
                        .WithMany("TagPrompts")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prompt");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PromptBE.Models.Category", b =>
                {
                    b.Navigation("CategoryPrompts");
                });

            modelBuilder.Entity("PromptBE.Models.Prompt", b =>
                {
                    b.Navigation("CategoryPrompts");

                    b.Navigation("TagPrompts");
                });

            modelBuilder.Entity("PromptBE.Models.Tag", b =>
                {
                    b.Navigation("TagPrompts");
                });
#pragma warning restore 612, 618
        }
    }
}
